# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  - repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '591568c9-fdc7-46e6-a1f2-0533e1ac1686'
  imageRepository: 'deepsea'
  containerRegistry: 'zulucontainerregistry.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'zulucontainerregistry6327d626-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Check
  displayName: Check Stage
  jobs:
    - job: Check
      displayName: Check
      pool:
        vmImage: $(vmImageName)
      steps:
        - task: SonarQubePrepare@4
          inputs:
            SonarQube: 'Sonar Connection'
            scannerMode: 'CLI'
            configMode: 'manual'
            cliProjectKey: 'Durgesh-coder-ust_AKS_DevOps'
            cliProjectName: 'AKS_DevOps'
            cliSources: '.'
            extraProperties: |
              # Additional properties that will be passed to the scanner,
              # Put one key=value per line, example:
              sonar.organization=durgesh-coder-ust

        - task: SonarQubeAnalyze@4

        - task: SonarQubePublish@4
          inputs:
            pollingTimeoutSec: '300'

        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm test
            npm run-script build
          displayName: 'npm install and build'
